# How many times to run the browser in each sample.
# Must be at least two, so we can calculate the sample standard deviation.
sample_size = 30

# Command for traceconv. The example below is for NixOS.
traceconv_command = ["steam-run", "../../traceconv"]

# Command for setting up CPU isolation. Must accept the same arguments as isolate-cpu-for-shell.sh.
# isolate_cpu_command = ["true"]  # on platforms without CPU isolation support
isolate_cpu_command = ["sudo", "../../isolate-cpu-for-shell.sh"]  # on Linux

# Define your CPU configs here.
# - Syntax is `key = [list of CPUs]`
# - Dots in the key must be quoted
[cpu_configs]
2cpu = [14, 15]
4cpu = [12, 13, 14, 15]
6cpu = [10, 11, 12, 13, 14, 15]
8cpu = [8, 9, 10, 11, 12, 13, 14, 15]

# Define your sites here.
# - Syntax is `key = "url"` or a `[sites.key]` table (see below)
# - Dots in the key must be quoted
# - If `url` has the root path (`/`), the trailing slash must be included
[sites]
"servo.org" = "https://servo.org/"

# Sites can also have other settings, in the full table format.
# - `url` has the same meaning as the string value above
# - `browser_open_time` (optional) is in seconds
# - `user_agent` (optional) overrides the browser’s default user agent
#   - Currently supported for `ServoDriver` and `ChromeDriver`-type engines only
#   - For `Servo`-type engines, use `extra_engine_arguments.engine = ["--user-agent", "Android"]`
#   - For `Chromium`-type engines, use `extra_engine_arguments.engine = ["--user-agent=Android"]`
# - `screen_size` (optional) overrides the browser’s reported screen size (not the viewport size!)
#   - Currently supported for `ServoDriver` and `ChromeDriver`-type engines only
#   - For `Servo`-type engines, use `extra_engine_arguments.engine = ["--screen-size", "320x568"]`
#   - For `Chromium`-type engines, there is no way to do this
# - `wait_for_selectors` (optional) is a map from CSS selectors to expected element counts
#   - Currently supported for `ServoDriver` and `ChromeDriver`-type engines only
#   - For `Servo`-type engines, there is no way to do this
#   - For `Chromium`-type engines, there is no way to do this
# - `extra_engine_arguments` (optional) is keyed on the engine key
# [sites."example.com"]
# url = "http://example.com/"
# browser_open_time = 20
# user_agent = "Android"
# screen_size = [320,568]
# wait_for_selectors."nav a" = 3
# extra_engine_arguments.servo1 = ["--pref", "dom.svg.enabled"]
# extra_engine_arguments.servo2 = ["--pref", "dom.svg.enabled"]

# Define your engines here.
# - Syntax is `key = { type = "Servo|Chromium", path = "/path/to/browser" }`
# - Dots in the key must be quoted
# - `type` is one of the following:
#   - `Servo` uses benchmark-servo.sh
#   - `Chromium` uses benchmark-chromium.sh
#   - `ServoDriver` runs servoshell and controls it with Servo’s WebDriver support
#   - `ChromeDriver` uses ChromeDriver, a WebDriver-based approach
# - If `path` has no slashes, it represents a command in your PATH
# - `description` (optional) is shown in the report
[engines]
"servo1" = { type = "Servo", path = "/path/to/servo1/servo" }
"servo2" = { type = "ServoDriver", path = "/path/to/servo2/servo" }
"chromium1" = { type = "Chromium", path = "google-chrome-stable" }
"chromium2" = { type = "ChromeDriver", path = "google-chrome-stable" }
